#!/bin/sh

echo 'copying to tmp..'
tmp=/tmp/acp_`date +%s%N`
mkdir $tmp || exit
mkdir $tmp/DEBIAN || exit

mkdir -p $tmp/usr/bin || exit
cp bin/acp $tmp/usr/bin || exit

mkdir -p $tmp/usr/share/apps/acp || exit
cp share/* $tmp/usr/share/apps/acp || exit

mkdir -p $tmp/usr/share/perl5/WWW || exit
cp -R lib/WWW/* $tmp/usr/share/perl5/WWW || exit

if [ "$1" != "--no-net-https-nb" ]
then
	mkdir -p $tmp/usr/share/perl5/Net/HTTPS || exit
	wget -O- http://search.cpan.org/CPAN/authors/id/O/OL/OLEG/Net-HTTPS-NB-0.11.tar.gz |
		tar -Oxvzf - Net-HTTPS-NB-0.11/lib/Net/HTTPS/NB.pm > $tmp/usr/share/perl5/Net/HTTPS/NB.pm || exit
fi

size=`du -ks $tmp/usr/ | cut -f1`
version=`egrep -o 'ACP_VERSION[[:space:]]+=>[[:space:]]+[[:digit:].]+' bin/acp | egrep -o '[[:digit:].]+'`

echo \
"Package: acp
Version: $version
Architecture: all
Maintainer: Oleg G <verdrehung@gmail.com>
Installed-Size: $size
Depends: perl, libgtk2-perl, libgtk2-notify-perl, libgtk2-gladexml-perl, libio-socket-ssl-perl, liburi-perl, libnet-http-perl | libwww-perl
Section: perl
Priority: optional
Description: ACP - Academ.org Control Panel for Linux
 Academ.org Control Panel for Linux helps users of Academ.Org network to work with their accounts" > $tmp/DEBIAN/control
 
echo 'packing...'
fakeroot dpkg-deb -b $tmp . || exit

echo 'cleaning...'
rm -rf $tmp

echo 'done'
