#!/bin/bash

die()
{
	echo "$1" >&2
	exit 1;
}

[ -e 'acp' ] || die "file ./acp doesn't exists";

if grep /usr/share/apps/acp/ acp >/dev/null
then
	sed -i 's@/usr/share/apps/acp/@share/@; s@#!/usr/bin/perl@#!/usr/bin/perl -I lib@' acp
	echo '/usr/share/apps/acp/ --> share/'
elif grep share/ acp >/dev/null
then
	sed -i 's@share/@/usr/share/apps/acp/@; s@#!/usr/bin/perl -I lib@#!/usr/bin/perl@' acp
	echo 'share/ --> /usr/share/apps/acp/'
else
	die "can't reconfigure acp"
fi

echo "done";
