#!/bin/sh

die()
{
	echo "$1" >&2
	exit 1;
}

ACP=bin/acp
[ -e $ACP ] || die "file $ACP doesn't exists";

if grep /usr/share/apps/acp/ $ACP >/dev/null
then
	sed -i 's@/usr/share/apps/acp/@share/@; s@#!/usr/bin/perl@#!/usr/bin/perl -I lib@' $ACP
	echo '/usr/share/apps/acp/ --> share/'
elif grep share/ $ACP >/dev/null
then
	sed -i 's@share/@/usr/share/apps/acp/@; s@#!/usr/bin/perl -I lib@#!/usr/bin/perl@' $ACP
	echo 'share/ --> /usr/share/apps/acp/'
else
	die "can't reconfigure $ACP"
fi

echo "done";
